"""Add is_admin field to User model

Revision ID: 257961b5b482
Revises: b02ee5abfe44
Create Date: 2025-05-04 14:09:47.097935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257961b5b482'
down_revision = 'b02ee5abfe44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_column('payment', 'updated_at')
    # ### end Alembic commands ###
